server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1
        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info